# Generated by Django 3.1.3 on 2020-11-30 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20201129_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_reg',
            new_name='Studentreg',
        ),
    ]
